export const RoutePath = {
  Home: "/",
  Login: "/login",
  Register: "/register",
  ExpertRegister: "/experts/register",
  ExpertRegisterVerifyEmail: "/experts/register/verify-email",
  ExpertApplication: "/experts/apply",
  SetPassword: "/set-password",
  AdminLogin: "/admin/login",
  Dashboard: "/dashboard",
  UserDashboard: "/dashboard/user",
  ExpertDashboard: "/dashboard/expert",
  ExpertWorkshops: "/dashboard/expert/workshops",
  ExpertWorkshopCreate: "/dashboard/expert/workshops/create",
  ExpertWorkshopDetail: "/dashboard/expert/workshops/:id",
  ExpertWorkshopEdit: "/dashboard/expert/workshops/:id/edit",
  ExpertWorkshopCohortCreate: "/dashboard/expert/workshops/:workshopId/cohorts/create",
  ExpertWorkshopCohortDetail:
    "/dashboard/expert/workshops/:workshopId/cohorts/:cohortId",
  ExpertWorkshopCohortEdit:
    "/dashboard/expert/workshops/:workshopId/cohorts/:cohortId/edit",
  ExpertWorkshopCohortMembers:
    "/dashboard/expert/workshops/:workshopId/cohorts/:cohortId/members",
  UserProfile: "/profile",
  AdminDashboard: "/dashboard/admin",
  AdminUsers: "/admin/users",
  AdminExpertApplications: "/admin/expert-applications",
  AdminExpertApplicationDetail: "/admin/expert-applications/:id",
  Workshops: "/workshops",
  Exchanges: "/exchanges",
  Community: "/community",
  Settings: "/settings",
  Notifications: "/notifications",
  PublicProfile: "/user/:id",
  PublicWorkshopDetail: "/workshops/:id",
  TestRoute: "/test",
} as const;
