export const RoutePath = {
  Home: "/",
  Login: "/login",
  Register: "/register",
  ExpertRegister: "/experts/register",
  ExpertRegisterVerifyEmail: "/experts/register/verify-email",
  ExpertApplication: "/experts/apply",
  SetPassword: "/set-password",
  AdminLogin: "/admin/login",
  Dashboard: "/dashboard",
  UserDashboard: "/dashboard/user",
  ExpertDashboard: "/dashboard/expert",
  ExpertWorkshopCreate: "/dashboard/expert/workshops/create",
  UserProfile: "/profile",
  AdminDashboard: "/dashboard/admin",
  AdminUsers: "/admin/users",
  AdminExpertApplications: "/admin/expert-applications",
  AdminExpertApplicationDetail: "/admin/expert-applications/:id",
  Workshops: "/workshops",
  Exchanges: "/exchanges",
  Community: "/community",
  Settings: "/settings",
  Notifications: "/notifications",
  PublicProfile: "/user/:id",
  TestRoute: "/test",
} as const;
